version: '3'
services:
  x-ui:
    image: mhsanaei/3x-ui
    container_name: 3x-ui
    ports:
      - "2053:2053"
      - "80:80"
    restart: always
    environment:
      - TZ=Asia/Tehran
    volumes:
      - ./config:/etc/x-ui
